<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SentinelVMS.Application\SentinelVMS.Application.csproj" />
    <ProjectReference Include="..\SentinelVMS.Domain\SentinelVMS.Domain.csproj" />
    <ProjectReference Include="..\SentinelVMS.Networking\SentinelVMS.Networking.csproj" />
    <ProjectReference Include="..\SentinelVMS.Streaming\SentinelVMS.Streaming.csproj" />
    <ProjectReference Include="..\SentinelVMS.Rendering\SentinelVMS.Rendering.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
